Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named 
“FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and 
mean squared error. (Wherever required remove null values, convert categorical data into numeric data) (Print Output wherever required)

<h1>TASK 1</h1>
<h3>Objective:</h3>
<h4>For the givencsv, write a python program satisfying following tasks to demonstrate application of machine learning through 
multiple linear regression as follows – </h4>
<h3>Dataset:</h3>
<h4>RealEstate.csv</h4>
<h3>Steps to Complete the Task:</h3>
<h4>
1. Import required libraries.<br>
2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.<br>
3. Remove ‘No’ column from the dataframe.<br>
4. Check for any null values in features using appropriate method.<br>
5. Create feature variables x and y as given above.<br> 
6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.<br>
7. Create and fit regression model using appropriate method.<br>
8. Use testing set created in step 6 to find and print the prediction of the outcome.<br>
9. Find and print coefficient and mean squared error of the regression model.</h4>

# Multiple Linear Regression – RealEstate Dataset

In [1]:
# 1. Import required libraries.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression

In [2]:
# 2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.

df = pd.read_csv("RealEstate.csv")

print(df.head())
print("\n-----------------------------")
print(df.info())
print("\nData Types:---------------------------------")
print(df.dtypes)
df

   No  X1 transaction date  X2 house age  \
0   1             2012.917          32.0
1   2             2012.917          19.5
2   3             2013.583          13.3
3   4             2013.500          13.3
4   5             2012.833           5.0

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10
1                               306.59470                                9
2                               561.98450                                5
3                               561.98450                                5
4                               390.56840                                5

   X5 latitude  X6 longitude  Y house price of unit area
0     24.98298     121.54024                        37.9
1     24.98034     121.53951                        42.2
2     24.98746     121.54391                        47.3
3     24.98746     121.54391                        54.8
4     24.97937     121.54245                        43.1

-----------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB
None

Data Types:---------------------------------
No                                          int64
X1 transaction date                       float64
X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [26]:
# 3. Remove ‘No’ column from the dataframe.

df.drop("No", axis = 1, inplace = True)

In [27]:
# 4. Check for any null values in features using appropriate method.

print("\nNull Values:---------------------")
print(df.isnull().sum())

Null Values:---------------------
X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [28]:
# 5. Create feature variables x and y as given above.

# Typical RealEstate dataset columns look like:

# X1 transaction date
# X2 house age
# X3 distance to MRT
# X4 number of convenience stores
# X5 latitude
# X6 longitude
# Y house price of unit area


X = df.drop("Y house price of unit area", axis = 1)
y = df["Y house price of unit area"]

In [29]:
# 6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.

from sklearn.model_selection import train_test_split

# 70% of data for training and with random state of 110.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, 
    test_size=0.7, 
    random_state=110
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(124, 6)
(290, 6)
(124,)
(290,)

In [30]:
# 7. Create and fit regression model using appropriate method.

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [31]:
# 8. Use testing set created in step 6 to find and print the prediction of the outcome.

y_pred = model.predict(X_test)
print("\nPredicted Values:--------------")
print(y_pred)

Predicted Values:--------------
[35.63915435 28.74866921 26.301066   41.00785297 34.41265822 42.34507695
 36.16989864 48.69739265 39.45181338 35.45505898 32.6219051  31.76419278
 40.35310159 18.94989011 32.98732435 33.83077824 36.19751323 43.65414952
 44.7400969  40.28597103 36.24306201 51.92906205 40.03005892 33.75705996
 43.27683388 39.81657752 46.37786816 39.33773534 39.47602553 48.63918744
 42.15398774 37.11016198 34.87627579 42.52321328 16.49733074 29.15336501
  1.28531175 39.46280856 45.02092131 32.76522613 40.54996034 46.86786191
 35.78991092 35.30584318 28.31815664 44.81578324 38.45475662 34.58908652
 27.93819756 46.48418433 36.51028071 39.59913001 46.58899859 45.1419108
 51.30496396 17.02429863 44.02194832 42.11565008 35.83051258 36.53106598
 42.0868533  41.2872474  45.9278284  37.13594574 39.18328586 20.80174352
 45.02092131 41.50593433 33.77842843 43.78396532 41.33807035 38.53099289
 45.13249933 32.18466328 42.44485145 36.80712348 39.33940056 42.96679287
 33.7863844  23.37257926 18.754767   44.35816931 42.54985328 10.50220837
 33.08774112 47.33042894 45.42891905 15.62408569 45.53486468 46.19434586
 35.31109553 34.96925549 33.24231624 43.62178517 41.09710704 38.62446291
 15.65853236 40.39578844 26.09747062 43.46567978 29.8667292  30.35703404
 43.88697561 47.7482213  41.43278783 42.08761913 46.58150435 35.21146044
 32.45192869 38.58660186 40.28297165 27.4805905  47.44557166 38.00994309
 15.65853236 44.58829421 11.42584868 37.9402315  35.30654709 45.42891905
 34.75879495 27.63146887 45.63106304 44.7640045  50.28951219 28.48943621
 46.3642491  31.13862846 42.15355046 33.91855251 46.0840139  47.1555041
 41.15543972 40.40853625 42.12926913 24.87380708 42.74443809 14.23027908
 36.07676635 46.11044502 23.77294368 19.73435226 39.88044337 32.89035417
 12.84787517  9.84110739 30.11170636 42.75423012 36.39358859 27.03785949
 33.57933173 39.25925349 18.50615143 46.69378746 52.7958024  41.21969313
 44.51180287 46.60777886 18.96350916 34.22775766 43.05304753 27.16772312
 42.19893607 47.58099245 47.43186577 28.82127342 34.39400951 45.49813451
 36.2564133  33.32016235 35.84821339 42.9812335  32.56935156 40.86764569
  7.78448803 41.53268587 39.96884717 45.05333511 28.63515602 34.02352159
 44.06934063 39.25925349 30.87720887 45.453598   38.90093861 48.05195179
 36.60756856 38.6452595  41.95171158 34.92810678 37.86712678 25.66519015
 46.9334174  40.35310159 35.3842646  40.05048621 37.88074583 45.80282132
 48.36812763 30.37820242 15.8445348  13.14027424 51.05171497 33.44878502
 26.4848012  34.64858056 25.7673979  25.77531172 28.90561587 34.80388433
 46.87539149 25.59891806 32.38318399 34.29202933 51.13851949 46.19904917
 29.39458437 29.68500145 42.19893607 35.58731921 42.33281889 13.90082588
 35.00002272 33.86495968 27.64149608 40.88318021 47.6708102  43.67121257
 35.46423797 45.86142429 24.61783555 46.30927844 47.33574695 47.33574695
 44.53795291 42.28599869 14.11406643 36.16776946  2.73026023 38.93252542
 40.5304925  45.06865933 41.86633332 33.5161473  31.50483862 13.51949241
 33.88076932 36.54054997 37.83284345 23.09795626 53.66254274 44.08295969
 43.03052381 19.8302495  40.20614091 40.35165961 36.71495374 10.57272739
 23.94532852 48.25217935 37.10464981 39.47602553 40.90319355 44.60533195
 29.42323356 42.14871357 33.94568779 40.97524074 30.63148847 44.86029652
 18.8282542  44.0638241  42.94987645 30.90413646 24.58219804 35.15876968
 35.06492717 31.77768579 46.11493304 41.22011296 44.91439218 44.55677156
 48.32737188 48.13207339 45.55483896 44.53375251 45.63106304 45.59165952
 35.51190912 41.41670068]

In [32]:
# 9. Find and print coefficient and mean squared error of the regression model.

print("Regression Coefficients / Slope:", model.coef_)
print("\nIntercept:", model.intercept_)

mse = mean_squared_error(y_test,y_pred)
mae = mean_absolute_error(y_test, y_pred)

print("\nMean Squared Error:", mse)
print("\nMean Absolute Error:", mae)

Regression Coefficients / Slope: [ 1.06067397e+01 -1.36190526e-01 -4.94982109e-03  1.13338051e+00
  7.53265320e+01  4.68068147e+00]

Intercept: -23762.876268070402

Mean Squared Error: 93.07119451879468

Mean Absolute Error: 6.817175569854635

In [33]:
# ----(OPTIONAL)-----For Model Saving / Saving Python objects to a file for later use.

import pickle

# Save only the trained model (no poly here)
with open("RealEstate.pkl", "wb") as file:
    pickle.dump(model, file)

print("Multiple Linear Regression Model Saved Successfully")

Multiple Linear Regression Model Saved Successfully

<h1>TASK 2</h1>
<h3>Objective:</h3>
<h4>Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named “winequality.csv”</h4>
<h3>Dataset:</h3>
<h4>Winequantity.csv</h4>
<h3>Steps to Complete the Task:</h3>
<h4>
Do the required process in the data before making a model. <br>
If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.<br>
Find co-efficient, intercept and mean squared error. Also, Predict the quality of red wine for the following data:  <br>                     
fixed acidity: 8    <br>        
vola le acidity: 0.4     <br>  
citric acid: 0.40  <br>              
residual sugar: 15   <br>       
chlorides: 0.048  <br>                
free sulfur dioxide: 40      <br>
total sulfur dioxide: 150 <br>    
density: 0.99   <br>               
pH: 3  <br>                    
sulphates: 0.45  <br>              
alcohol: 10.5</h4>

# Linear Regression – Wine Quality Prediction

In [60]:
# 1. Do the required process in the data before making a model.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [61]:
# 2. Load Dataset

df = pd.read_csv("winequality.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [62]:
# 3. Check Dataset Information

print(df.info())
print("--------------------------")
print(df.describe())
print("------------------------------")
print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB
None
--------------------------
       fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000
mean        8.311111          0.531339     0.268364        2.532152
std         1.747595          0.179633     0.196686        1.355917
min         4.600000          0.120000     0.000000        0.900000
25%         7.100000          0.392500     0.090000        1.900000
50%         7.900000          0.520000     0.250000        2.200000
75%         9.100000          0.640000     0.420000        2.600000
max        15.900000          1.580000     1.000000       15.500000

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000
mean      0.086933            15.615486             45.914698     0.996730
std       0.047267            10.250486             32.782130     0.001925
min       0.012000             1.000000              6.000000     0.990070
25%       0.070000             7.000000             21.000000     0.995570
50%       0.079000            13.000000             37.000000     0.996680
75%       0.090000            21.000000             61.000000     0.997845
max       0.611000            68.000000            289.000000     1.003690

                pH    sulphates      alcohol      quality           Id
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000
mean      3.311015     0.657708    10.442111     5.657043   804.969379
std       0.156664     0.170399     1.082196     0.805824   463.997116
min       2.740000     0.330000     8.400000     3.000000     0.000000
25%       3.205000     0.550000     9.500000     5.000000   411.000000
50%       3.310000     0.620000    10.200000     6.000000   794.000000
75%       3.400000     0.730000    11.100000     6.000000  1209.500000
max       4.010000     2.000000    14.900000     8.000000  1597.000000
------------------------------
fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [63]:
# 4. Handle Missing Values 

print(df.isna().sum())

df = df.fillna(df.mean(numeric_only=True))

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [64]:
# 5. Define Feature Variables (X) and Target (y)

# In wine dataset:
# Features → chemical properties
# Target → quality

X = df.drop(["quality",'Id'],axis = 1)
y = df["quality"]

In [65]:
# 6. Split Data into Training and Testing Sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.7, random_state = 42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(342, 11)
(801, 11)
(342,)
(801,)

In [66]:
# 7. Create and Train Linear Regression Model

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [67]:
# 8. Predict Wine Quality on Test Data

y_pred = model.predict(X_test)

print("Predicted Values:-----------------\n",y_pred)

Predicted Values:-----------------
 [5.41018158 4.86174195 5.2343045  5.20282654 6.16973546 6.62472537
 5.36235608 5.10178407 5.80111963 5.35031123 6.30923998 6.30255553
 5.49467954 6.23330723 5.93139774 4.86228581 5.76256854 5.7547717
 5.53545019 6.43903066 6.05247293 6.24502072 5.15617239 6.45722472
 5.65495806 5.12557543 6.61399818 5.97492094 5.12924034 5.59537746
 6.26876725 5.47016458 6.56734201 5.78686825 5.61352881 5.17005344
 5.45426723 6.07474958 6.87949652 6.07588134 6.37517037 5.4236388
 6.93556439 5.38715446 5.13727853 5.13203638 5.65737855 5.83050903
 4.59051577 5.73728573 6.49670789 5.22377177 5.64083117 5.918106
 5.7461544  6.38220629 5.56363946 5.77889375 6.0128935  5.28180532
 5.55102885 5.99935334 5.68933951 6.32884712 6.19832859 5.41772154
 6.81196382 5.29197074 4.89152872 6.04041629 5.69621719 5.32411205
 5.70605436 6.01740369 5.19208217 5.21987204 5.96708661 5.87476031
 5.67433384 5.42068733 5.40600579 5.60715117 5.90053534 5.32184866
 5.57022454 5.97216349 5.50983596 5.69662131 5.82001211 5.30412979
 4.80226937 5.58653123 5.01861405 5.1022235  5.13507819 5.14823774
 5.36606182 6.39297925 6.03326001 5.5580987  5.74543232 6.36268251
 5.20362501 6.07344811 5.23528    5.28824019 5.87946853 6.17960602
 5.62181761 6.45651992 5.86141425 5.30670939 5.57842305 6.07550258
 5.00603165 5.12544971 5.34143637 6.51578337 5.81800075 4.85533014
 5.24423686 4.9407191  5.56311567 6.10836479 5.24201205 5.69851561
 5.74768822 5.80903784 5.26526696 6.39076642 5.08306305 4.93570072
 5.81591841 5.7565463  7.52603389 4.80644099 4.29450501 5.51059193
 5.65821331 5.77434849 6.90731946 5.37056749 5.66998184 4.84641047
 6.47360918 5.11180091 5.08109524 5.43023041 4.91480549 4.94730257
 6.46755035 5.36418768 6.20515656 5.30643218 5.96283839 5.7869783
 5.43023041 5.8203579  6.27076385 5.71571277 5.98025981 5.07227469
 5.74710014 5.61531496 5.73628972 5.40300854 6.10831934 6.12527649
 5.53092584 5.14755842 6.54982819 5.44582283 5.44327624 5.69837724
 5.24181232 5.19235464 6.37030049 5.89852488 5.6183856  5.37974334
 6.11259373 5.77012911 5.68181702 5.43071092 5.12322615 5.26064144
 6.17735493 4.87917201 6.31486607 5.71235836 5.7754495  5.75351444
 6.60778338 5.77363174 5.58231897 5.46815259 5.12322404 6.55798298
 6.55205512 6.29608135 5.85371019 5.72693732 5.27173071 5.50053643
 5.85122472 5.57553915 5.06665062 5.22422379 6.13731561 6.09972191
 5.08500236 6.1123714  5.48543009 5.73401359 5.55301001 5.10286564
 6.55755472 5.1115862  6.14270317 5.73172629 5.72467445 5.46072432
 5.11625587 5.77673715 4.81513474 6.05345675 5.40146614 5.58608308
 5.79629181 5.80676606 6.43207612 6.41513629 5.07716189 5.22281399
 5.8952796  6.64327785 4.94863451 5.67527009 5.61221305 5.33318935
 6.27084874 6.22578526 6.02173251 5.28755814 6.14382721 5.71202758
 5.06086049 5.67365937 6.08083085 5.34554581 5.32922392 5.29056677
 5.88325167 6.09187917 4.93742281 6.11235576 6.1519302  5.56625325
 5.18503529 5.16550572 5.69851561 5.46815259 6.45346032 5.30556451
 5.04584999 4.83875873 5.84629361 6.2791777  5.23183711 6.15746715
 5.21957909 6.7235296  5.69668526 6.26758778 5.0809564  5.73235931
 5.34769063 6.09187917 5.50645336 5.55777638 5.39341489 6.32751016
 5.06604586 4.79860388 5.57772063 6.52032125 5.13226001 5.12792701
 5.65651161 6.01106224 5.97729617 5.16196857 6.4931765  5.56997499
 5.92164657 5.5071888  6.42519308 5.19331966 5.96834786 5.41220492
 5.15082464 6.02023942 6.178459   5.50875922 5.22854082 4.93539801
 5.85231621 6.08175765 6.48291078 5.63398723 5.79462602 6.42807374
 5.82739777 5.19553666 5.5065241  5.33905111 4.99876747 5.23469924
 5.60542093 5.15670692 5.14860952 5.96708661 5.512012   5.28030195
 5.20998284 6.23068872 6.1967685  4.8462235  5.52313454 5.12937489
 6.42862626 5.40300854 5.34224618 6.64373454 5.37329371 5.17615937
 6.21382316 4.70599385 6.33543418 5.37277609 5.98151865 5.20485686
 5.00210078 4.42678798 5.35031123 4.43512771 6.03055391 5.10273632
 4.98492026 6.62281779 5.71242377 5.50875922 6.2570277  5.3174059
 6.05129784 5.0025033  5.71878066 5.55100998 6.33145852 6.41952956
 5.48085576 5.75359935 6.39057106 5.8489932  5.80272303 5.46781459
 6.61415902 5.70203579 6.09173917 5.10263363 5.16127146 5.24444757
 5.35998046 5.34692103 4.56690317 5.221335   6.236466   5.57553915
 5.84841448 5.69027507 5.53147353 5.68411955 6.15900585 5.52736521
 5.74212747 5.68107268 5.47085129 5.78226248 5.68869012 6.34568551
 5.61850572 5.61437507 5.38489913 5.75024517 5.21957909 5.15239626
 5.13022946 6.03903998 5.77434849 5.37655599 5.28334661 5.5711335
 5.61795167 6.1166542  6.05285593 5.06987563 5.94773737 5.06963826
 5.16105137 5.41824575 6.83291189 5.66839186 6.5320203  5.8634988
 6.22055837 5.96181816 6.17249706 6.44912711 5.18708195 6.60701141
 5.06987563 6.02371457 6.30189867 5.35104737 5.1569092  5.09685013
 5.18506509 5.39023982 6.31486607 5.49467954 5.17266911 5.83428281
 5.13411945 5.53545019 6.11498526 6.02841538 5.73740219 5.05815439
 5.67220422 5.18303179 5.80989755 5.65743308 5.38411997 5.33824502
 5.7754495  6.16968036 5.77326554 5.19598461 6.20541979 5.2583941
 5.6337149  5.95667044 5.60567496 4.9265991  5.03285896 5.29909534
 5.16898411 5.17138716 5.63709356 5.42320529 5.19173794 5.44703234
 5.59537746 5.34799273 6.49789333 5.9063615  6.3859228  5.14195877
 6.9443716  5.61155068 5.5300839  5.6284825  6.26065121 6.34568551
 4.77148989 5.25624894 5.26938806 5.73401359 4.98570475 5.30759479
 5.42927348 5.45896796 5.68107268 5.29235739 6.59116493 6.04435286
 5.41154588 6.65457223 6.08989753 6.19865346 5.63475768 5.31394858
 5.48640183 5.1712357  5.51180145 5.90192295 5.74660407 6.47317468
 6.45651992 5.96909027 5.70601929 6.65483084 6.36647671 4.8746225
 5.00715131 5.46745026 5.53148839 5.17656385 6.56563075 5.79110559
 6.09631811 5.79502187 5.03551421 5.98783867 5.65841205 5.0193962
 6.15581111 5.70912862 5.10026565 5.37226517 5.15861533 5.74553446
 5.930463   5.90384328 5.53092584 5.44439112 5.56425787 5.17404899
 4.73902958 5.15268663 5.05684202 6.85714891 5.32578544 6.11089263
 5.24444757 5.04533276 5.37578218 6.1967685  5.27656706 5.89253125
 5.303984   5.67569982 5.39011117 5.15411663 5.50911543 6.11498526
 5.61352186 5.74990221 5.56465934 5.74788136 5.53148839 5.159023
 5.65486632 5.09329295 5.41961434 6.1041291  5.7541039  5.16287096
 5.33648245 5.4083621  5.96940608 5.28756649 5.66868454 5.0387588
 6.16968036 6.14930583 4.73358392 5.44717866 5.55777638 6.45884627
 4.9809435  5.3980862  5.65314848 5.94185489 5.44494808 5.57848136
 5.3526601  5.40158237 5.07113973 6.72244292 5.65565343 5.06816488
 5.96980252 5.20559343 5.98452925 6.37929873 6.28057563 6.16449127
 6.60479417 5.34315321 5.73560502 5.45948908 5.4871564  5.07113973
 5.88609099 5.8886796  5.67784087 5.8666763  5.94457661 4.93570072
 5.32387839 4.94791208 6.18381624 6.03998179 5.22587845 5.16305445
 6.63515607 6.92640906 5.34692103 5.45271723 6.23601275 5.17404899
 5.8122866  5.22673802 5.12792701 6.02236937 5.46024621 5.91008473
 5.08433254 5.01698578 6.06097182 5.85440827 5.30004925 5.88499201
 6.14683248 5.30412979 5.65315918 5.07074938 6.21139978 5.74695674
 5.0740674  5.60715117 5.79538629 5.41897503 5.25709334 5.47911755
 5.5524378  5.89145931 4.9446788  5.3973867  5.18748597 5.80903784
 5.39713519 5.10178007 5.79621436 5.51244355 5.43684777 5.69419618
 6.53468249 5.12583755 5.07196685 5.53582675 5.46335314 5.05353799
 4.79410568 5.49570642 5.18464336 6.30923998 6.30366988 6.07948432
 6.31766515 5.55975069 6.5806325  6.36071145 6.33900674 6.17969315
 5.39625145 6.13656977 5.26671155 6.39278762 5.09435266 5.43237548
 5.70096804 6.031902   5.46300895 5.15352944 5.67330594 5.29835297
 6.4287734  6.82088989 5.34315321 6.04641365 5.93042226 5.98004117
 5.27839559 5.81540984 5.2818287  5.18343019 5.77434849 5.97138086
 5.36111615 6.62718862 5.70691191 5.75257104 4.89908953 5.10545122
 5.03848895 5.29580791 5.17161294 5.82219693 5.28180532 5.98972152
 5.0185914  6.37487222 6.16752077 5.28334661 6.62718862 6.07210511
 5.82997465 6.07932529 5.52960039 6.21382316 5.48823205 5.84207399
 5.10026565 6.46335207 5.96131225 6.30938154 5.73872964 5.8203579
 5.13507819 5.880488   5.55887388 5.80554453 5.57842305 5.87983687
 5.85122472 5.92404955 5.18381213 5.48721377 5.81191534 6.18716589
 5.36412641 6.7182237  5.04966222 5.12569296 5.60316901 6.03737949
 5.16248938 5.32381669 6.20541979 5.99807664 6.06277167 6.07563368
 5.61002874 6.53542973 5.24524825 5.63825598 5.77840166 5.69844417
 5.21987204 5.01241021 6.25816523 5.56399706 5.96532271 5.7259596
 5.99044406 6.11498526 5.41572851 4.71069454 5.02291182 5.63744207
 6.33295288 6.41086417 5.37561902 5.29622129 6.57052478 5.15260246
 4.73542198 5.45065258 5.57843186 5.36235608 5.49467538 5.06117507
 5.39838022 6.39588525 6.62385199 5.02408492 5.39713519 5.73401359
 5.54314983 5.65756178 5.34375241 5.30428979 5.6460837  6.1399
 5.12120695 5.31047042 5.55100998 5.41961434 5.95431715 5.52960039
 5.19173794 5.23064186 5.64227171 6.14480674 5.33479212 5.17071587
 5.7784047  5.48823205 5.40697566]

In [68]:
# 9. Model Evaluation

print("Coefficient:---------\n", model.coef_)
print("\nIntercept:--------\n", model.intercept_)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:\n", mse)

Coefficient:---------
 [ 5.14790060e-02 -1.23264885e+00 -1.88270179e-01  2.67015318e-02
 -1.16884988e+00  1.00625566e-03 -3.30889117e-03 -3.59696134e+01
 -9.72904576e-02  6.47307956e-01  2.61213853e-01]

Intercept:--------
 39.135775429340804
Mean Squared Error:
 0.4202502035133486

In [69]:
# 10. Predict the quality of red wine for the following data:

# Input Values:
    
# | Feature              | Value |
# | -------------------- | ----- |
# | fixed acidity        | 8     |
# | volatile acidity     | 0.4   |
# | citric acid          | 0.40  |
# | residual sugar       | 15    |
# | chlorides            | 0.048 |
# | free sulfur dioxide  | 40    |
# | total sulfur dioxide | 150   |
# | density              | 0.99  |
# | pH                   | 3     |
# | sulphates            | 0.45  |
# | alcohol              | 10.5  |

# sample = [[8, 0.4, 0.40, 15, 0.048, 40, 150, 0.99, 3, 0.45, 10.5]]

sample = pd.DataFrame(
    [[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]],
    columns=X.columns
)


prediction = model.predict(sample)

print("Predicted Wine Quality:",prediction[0])

Predicted Wine Quality: 5.99982001658033

In [70]:
# ----(OPTIONAL)-----For Model Saving / Saving Python objects to a file for later use.

import pickle

# Save only the trained model (no poly here)
with open("winequality.pkl", "wb") as file:
    pickle.dump(model, file)

print("Multiple Linear Regression Model Saved Successfully")

Multiple Linear Regression Model Saved Successfully

<h1>TASK 3</h1>
<h3>Objective:</h3>
<h4>Consider variables x and y created from a pandas dataframe  “car.csv” .</h4>
<h3>Dataset:</h3>
<h4>car.csv</h4>
<h3>Steps to Complete the Task:</h3>
<h4>
Create new column named “Age_car” (Age_car=2023-year) <br>
For multiple linear regression problem, x contains the independent variables ( Age_car , Driven_kms , Fuel_Type , Selling_type , Transmission )  and y contains the dependent (Selling_Price) variable which is to be predicted.<br>
Write a Python program to spilt x and y into training and testing datasets with a 20% split. Then create a multiple linear regression model using the training data and print its coefficients ,intercept and mean squared error</h4>

# Industry-Correct Approach

In [71]:
# 1️⃣ Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

In [72]:
# 2️⃣ Load Dataset

df = pd.read_csv("car.csv")
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [73]:
# 3️⃣ Create New Column → Age_car

df['Age_car'] = 2023 - df["Year"]
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,9

In [74]:
# 4️⃣ Drop Unnecessary Columns

# Usually Car_Name is useless for regression:

df = df.drop(["Car_Name", "Year"], axis = 1)
df

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,9
...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,Diesel,Dealer,Manual,0,7
297,4.00,5.90,60000,Petrol,Dealer,Manual,0,8
298,3.35,11.00,87934,Petrol,Dealer,Manual,0,14
299,11.50,12.50,9000,Diesel,Dealer,Manual,0,6
300,5.30,5.90,5464,Petrol,Dealer,Manual,0,7

In [75]:
# 5️⃣ Handle Categorical Variables (VERY IMPORTANT)

df = pd.get_dummies(df,drop_first = True)
df

# This converts:

# Fuel_Type → Petrol/Diesel
# Transmission → Manual/Automatic
# Selling_Type → Dealer/Individual

,Selling_Price,Present_Price,Kms_Driven,Owner,Age_car,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,9,0,1,0,1
1,4.75,9.54,43000,0,10,1,0,0,1
2,7.25,9.85,6900,0,6,0,1,0,1
3,2.85,4.15,5200,0,12,0,1,0,1
4,4.60,6.87,42450,0,9,1,0,0,1
...,...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,0,7,1,0,0,1
297,4.00,5.90,60000,0,8,0,1,0,1
298,3.35,11.00,87934,0,14,0,1,0,1
299,11.50,12.50,9000,0,6,1,0,0,1
300,5.30,5.90,5464,0,7,0,1,0,1

In [76]:
# 6️⃣ Define X and y

X = df.drop("Selling_Price", axis = 1)
y = df["Selling_Price"]

In [77]:
# 7️⃣ Train-Test Split (20% Test)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)

In [78]:
# 8️⃣ Train Linear Regression Model

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [79]:
# 9️⃣ Predictions

y_pred = model.predict(X_test)
print(y_pred)

[ 2.95534303  8.178939    6.45427257 -1.42417501  9.08889914  7.41825441
  1.33644285  0.84027217  1.36501949  7.49026806  9.11830017  0.58573931
  8.41612774  3.42316502  6.90043281  3.04988309  0.48448171 10.70970753
  1.75207005  2.34571752  0.39746889  8.11925338  6.62469317  2.65939066
  0.78280554  3.69330765  5.24815462  2.82676351  2.13640446  1.75237686
  0.39730155  9.11750503 -0.66188053  2.29098014  8.57067341  4.4910324
  7.20530369  7.53824015  2.89101139  7.93588794  3.93585154  4.27133211
  4.33205704  0.6008847   7.34025071  0.47602539  7.29187681 11.23125597
  3.13805132  5.38262985  6.7988422   2.17888955 20.63303305 17.0015261
  7.50717349  9.69621308  4.47478116  8.97377615  1.82294639  7.60416734
  0.22226536]

In [82]:
# 🔟 Results

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

print("Coefficient:", model.coef_)
print("Intercept:", model.intercept_)

print("Accuracy: ",metrics.r2_score(y_test,y_pred))

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

Coefficient: [ 4.29152503e-01 -6.15725866e-06 -9.03759824e-01 -3.53801365e-01
  2.53327258e+00  7.38464226e-01 -1.19059291e+00 -1.63902155e+00]
Intercept: 5.787238551816784

NameError: name 'metrics' is not defined

In [81]:
# ----(OPTIONAL)-----For Model Saving / Saving Python objects to a file for later use.

import pickle

# Save only the trained model (no poly here)
with open("car.pkl", "wb") as file:
    pickle.dump(model, file)

print("Multiple Linear Regression Model Saved Successfully")

Multiple Linear Regression Model Saved Successfully