Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named 
“FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and 
mean squared error. (Wherever required remove null values, convert categorical data into numeric data) (Print Output wherever required)

<h1>TASK 1</h1>
<h3>Objective:</h3>
<h4>For the givencsv, write a python program satisfying following tasks to demonstrate application of machine learning through 
multiple linear regression as follows – </h4>
<h3>Dataset:</h3>
<h4>RealEstate.csv</h4>
<h3>Steps to Complete the Task:</h3>
<h4>
1. Import required libraries.<br>
2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.<br>
3. Remove ‘No’ column from the dataframe.<br>
4. Check for any null values in features using appropriate method.<br>
5. Create feature variables x and y as given above.<br> 
6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.<br>
7. Create and fit regression model using appropriate method.<br>
8. Use testing set created in step 6 to find and print the prediction of the outcome.<br>
9. Find and print coefficient and mean squared error of the regression model.</h4>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [2]:
# 1. Load Dataset

df = pd.read_csv("RealEstate.csv")
# df
df.head()
# df.info()
# df.describe()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [3]:
# 2. Check datatypes

print(df.dtypes)

No                                          int64
X1 transaction date                       float64
X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object

In [4]:
# 3. Drop "No"

df = df.drop("No", axis = 1)
df.head()
df

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...
409,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [5]:
# 4. Check null values

print(df.isna().sum())

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [6]:
# 5. Featurs & Targets 

X = df.drop("Y house price of unit area", axis = 1)
y = df["Y house price of unit area"]

print(X.shape, y.shape)

(414, 6) (414,)

In [7]:
# 6. train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size = 0.7, random_state = 110)
  
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(124, 6)
(290, 6)
(124,)
(290,)

In [8]:
# OPTIONAL STEP


from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

from sklearn import metrics

for i in range(1,11):
    poly = PolynomialFeatures(degree = i)
    X_poly = poly.fit_transform(X)
    model = LinearRegression()
    model.fit(X_poly, y)
    y_pred = model.predict(X_poly)
    print(f"R2_score:  {i} {metrics.r2_score(y_pred, y)}")

R2_score:  1 0.2828799011286146
R2_score:  2 0.584033435919276
R2_score:  3 0.18186246829063313
R2_score:  4 0.5918103908768737
R2_score:  5 0.7579523327688565
R2_score:  6 0.7520574505788309
R2_score:  7 0.8107887099799191
R2_score:  8 0.8153119423388412
R2_score:  9 0.8213901885027636
R2_score:  10 0.8246024615626297

In [9]:
# 7. Polynomial transformation (IMPORTANT)

poly = PolynomialFeatures(degree = 10)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

In [10]:
# 8. Train Model

model = LinearRegression()
model.fit(X_train_poly, y_train)

LinearRegression()

In [11]:
# 9. Prediction

y_pred = model.predict(X_test_poly)
print("Prediction:", y_pred)

Prediction: [ 5.54398392e+01 -1.20219321e+04  1.20409526e+03  8.08108634e+01
  1.88147801e+03  2.29084505e+03  1.62062234e+02  7.47279601e+01
 -2.46947180e+02  1.80008563e+02  1.47372350e+02  1.13107256e+04
  4.30862981e+02 -5.55874175e+05  4.85404231e+01  2.41560070e+02
  9.84316881e+01 -3.06509818e+01  3.00247585e+01  7.03522792e+01
  1.53842486e+03  6.24245288e+01  5.07233393e+01  9.82971492e+02
  5.45734960e+01 -1.68065327e+00  2.55634635e+02  6.02096226e+01
  3.51354896e+01  6.27749026e+01  3.26264926e+03  1.65597301e+03
 -1.61502611e+01  8.90228416e+01 -8.47428977e+05  3.64486109e+03
 -1.64229936e+10  4.97654633e+01  4.08111179e+01 -4.75055833e+01
 -7.63348700e+01  9.99797621e+01 -1.78960022e+02  2.62073993e+01
  1.14352031e+02  6.00329668e+01 -5.55066556e+00 -8.20447122e+02
  5.96537857e+03  6.80090350e+00  4.19211954e+01  8.64390461e+01
 -6.90642446e+01  5.78581566e+01  4.46104163e+00 -2.99139738e+05
  5.37264856e+01  4.99518121e+01  5.89141527e+02  2.15178083e+02
  5.37305605e+01  3.11360627e+03  5.02468552e+01  7.26980962e+01
  3.85930869e+01  9.32790728e+05  4.08111179e+01  2.19904759e+03
  1.77586628e+02 -2.37037190e+01  3.20747942e+01  8.63553453e+01
 -1.94787887e+02  5.72461160e+03  1.58361399e+02  7.60031036e+01
  4.29908342e+01  4.93316591e+01  7.71927920e+01 -3.28664774e+05
 -3.43007060e+05  2.88296349e+02 -2.68869391e+01  4.25640136e+05
  3.71526000e+02  1.93196759e+01  3.49063969e+02  2.17704051e+04
  4.70955141e+01 -1.49057401e+02  2.10933065e+03  1.10701374e+02
  2.73807430e+01 -1.08806418e+02  4.71874779e+01  5.00036442e+01
 -3.37718480e+05  5.48421277e+01  1.73389907e+04  4.43184727e+00
  1.90642166e+05  3.15749099e+02  3.93123500e+01  8.24774806e+01
  6.12686750e+01  5.47250268e+01  3.57558705e+01 -3.59618514e+03
  1.01301106e+04  7.86180285e+01  6.69158928e+01 -4.00144868e+01
  1.14729453e+02  4.80562153e+01 -3.37718480e+05  4.00003079e+01
 -1.36235858e+09  4.66231467e+01  9.60322810e+01  3.49063969e+02
  4.75345219e+01 -5.62279997e+06  1.97992736e+01  1.06259337e+02
  6.46233918e+01  1.00649769e+02  2.50829161e+02 -8.05594616e+02
  4.95370693e+01 -6.30785313e+03 -1.92832246e+02  1.28315279e+02
  8.68633389e+01 -6.63408508e+01  5.05874456e+01  1.80680532e+01
 -1.48245050e+02  4.60811200e+06  3.76230522e+02  6.77257468e+01
  8.95093119e+03 -2.66930184e+05  6.18060046e+02  1.15301220e+02
 -1.59666109e+05 -8.43130473e+09  4.00250079e+02 -2.13260533e+02
  7.99389525e+01 -5.96084679e+03  2.83435779e+04 -4.90958870e+01
  9.90236231e+06  2.17650236e+01  6.15026705e+01  5.12736441e+01
  9.63783395e+01  9.73366614e+01 -5.87616453e+05  2.06088594e+01
  3.49220768e+01  7.14234435e+02 -4.17346816e+03  1.12784611e+02
 -1.09711015e+02 -9.30767781e+02  7.93472481e+00  1.32629906e+02
  1.99821640e+02  1.73732183e+03  1.86772982e+01 -1.19630186e+02
  1.25497283e+01  7.47238238e+01 -1.29319886e+07  8.58665358e+01
 -2.44178843e+01  4.27539933e+01  2.63948628e+01 -1.86867239e+02
 -2.92833369e+01 -4.90958870e+01  5.40432623e+03  2.07387763e+00
 -8.22568942e+01  2.14783061e+01 -6.30706599e+01 -4.63170820e+00
  5.17710412e+01 -1.84968933e+02  6.69753454e+01 -6.15634467e+03
  2.23595204e+01  4.30862981e+02 -7.84262270e+00 -2.05351750e+01
  6.64628153e+01  1.36268997e+01 -4.17406368e+01 -2.17258354e+03
  7.30941615e+06  1.29976391e+01  6.07680642e+01  2.57078792e+01
  1.92857549e+02  1.33794538e+04 -1.01347861e+03  5.35951084e+00
 -8.91595393e+00  5.90911236e+02  5.18188846e+01 -5.49063016e+06
 -1.52673476e+02  5.06003231e+01  1.04396211e+02  3.31974810e+02
 -6.80883586e+00 -8.77630543e+02 -4.17346816e+03 -2.20618133e+02
  4.47199870e+02 -1.57950531e+04  3.20325345e+01  2.36809093e+03
  1.78300814e+04  4.91272451e+01  1.85646884e+02  3.73155491e+02
 -1.50521299e+01  5.08223891e+01  1.94111627e+05  3.34388683e+02
  1.32999613e+01  1.32999613e+01  3.61597756e+02  3.28905343e+03
  5.30942313e+06  3.98739629e+02 -6.50366747e+09  6.00609874e+01
 -5.69949806e+01  9.06571978e+01  1.71264391e+02  2.88553718e+01
 -2.86917339e+03 -5.49455978e+04  4.36583144e+01 -1.30116210e+02
  1.77663404e+02 -3.63217721e+05  5.79264085e+01 -3.89954262e+01
  1.19238946e+02 -6.22048533e+05  4.58153629e+01  9.28119231e+01
  2.67915245e+01 -1.37006718e+09 -1.09556559e+04  5.78270418e+01
 -1.25028920e+01  3.51354896e+01 -5.66387908e+01  5.32195550e+01
  6.10672266e+01  4.38754150e+01  2.29793114e+01  1.12497647e+02
  2.54844612e+01 -1.04491463e+02  5.46592564e+05  2.19058989e+02
 -1.28439934e+02  4.88526330e+02 -3.41224472e+03  3.33643650e+01
 -5.66735876e+02 -2.06043086e+03  2.86963841e+01  5.02341031e+01
  2.01935281e+01  1.21152733e+02  1.63755548e+02  5.13142210e+00
  1.24316337e+02  5.83684060e+01  1.97992736e+01  3.56458339e+01
  3.07586180e+02 -9.15000287e+01]

In [12]:
# 10. Metrics 

print("Coefficient:",model.coef_)
print("Intercept:", model.intercept_)

print("Mean Suqared Error:", mean_squared_error(y_test, y_pred))

print("Mean Absolute Error:", mean_absolute_error(y_test,y_pred))

print("Accuracy:",metrics.r2_score(y_test,y_pred))

Coefficient: [ 3.92054856e-23 -2.81069612e-25 -1.90597371e-25 ... -2.44915092e-32
  4.73351998e-32  1.04088007e-30]
Intercept: -30863824.079021037
Mean Suqared Error: 1.3339063790334044e+18
Mean Absolute Error: 117756006.2578206
Accuracy: -7007169705361955.0

In [14]:
# ----(OPTIONAL)-----For Model Saving / Saving Python objects to a file for later use.

import pickle

with open("RealEstate.pkl", "wb") as file:
    pickle.dump((poly,model), file)
    
print("Polinomial Model Saved Successfully")

Polinomial Model Saved Successfully

In [ ]:
plt.scatter()
plt.plot()

plt.show()

<h1>TASK 2</h1>
<h3>Objective:</h3>
<h4>Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named “winequality.csv”</h4>
<h3>Dataset:</h3>
<h4>Winequality.csv</h4>
<h3>Steps to Complete the Task:</h3>
<h4>
Do the required process in the data before making a model. <br>
If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.<br>
Find co-efficient, intercept and mean squared error. Also, Predict the quality of red wine for the following data:  <br>                     
fixed acidity: 8    <br>        
vola le acidity: 0.4     <br>  
citric acid: 0.40  <br>              
residual sugar: 15   <br>       
chlorides: 0.048  <br>                
free sulfur dioxide: 40      <br>
total sulfur dioxide: 150 <br>    
density: 0.99   <br>               
pH: 3  <br>                    
sulphates: 0.45  <br>              
alcohol: 10.5</h4>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [16]:
# 1.Load dataset

df = pd.read_csv("winequality.csv")
df
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [17]:
# 2. Check Datatypes

print(df.dtypes)

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [18]:
# 3. Fill missing values with mean

print(df.isna().sum())

df = df.fillna(df.mean(numeric_only = True))
df.head()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,2
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,3
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,4

In [19]:
# 4. Define Feature Variables (X) and Target(y)

X = df.drop(["quality","Id"], axis =1)
y = df["quality"]

print(X.shape)
print(y.shape)

(1143, 11)
(1143,)

In [20]:
# 5. train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(914, 11)
(229, 11)
(914,)
(229,)

In [ ]:
# 6. OPTIONAL STEP

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn import metrics

for i in range(1,11):
    poly = PolynomialFeatures(degree = i)
    X_poly = poly.fit_transform(X)
    model = LinearRegression()
    model.fit(X_poly, y)
    y_pred = model.predict(X_poly)
    print(f"R2 Score: {i} {metrics.r2_score(y_sspred, y)}")

R2 Score: 1 -0.6720658640184072
R2 Score: 2 -0.1986908105820313
R2 Score: 3 0.5311419296656315
R2 Score: 4 0.9996894871439305
R2 Score: 5 0.9999897298058212
R2 Score: 6 0.9999403275954009
R2 Score: 7 0.999142127777427
R2 Score: 8 0.9436373454927739
R2 Score: 9 0.9458115139151554

In [28]:
# Polynomial Transformation (IMPORTANT)

poly = PolynomialFeatures(degree = 10)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

In [ ]:
# 8. Train Model

model = LinearRegression()
model.fit(X_train_poly, y_train)

In [ ]:
# 9. Prediction

y_pred = model.predict(X_test_poly)
print('Prediction:', y_pred)

In [ ]:
# 10. Metrics 

print("Coefficient:",model.coef_)

print("Intercept:", model.intercept_)

print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

print("Mean Absolute Error:", mean_absolute_error(y_test, y_pred))

print("R2 Score:", metrics.r2_score(y_test, y_pred))

In [115]:
# 11. Prediction for given input

# input_data = [[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]]

sample = pd.DataFrame(
    [[8,0.4,0.40,15,0.048,40,150,0.99,3,0.45,10.5]],
    columns=X.columns
)

input_poly = poly.transform(input_data)

C:\Users\vidhu\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(

In [116]:
prediction = model.predict(input_poly)

print("Predicted Wine Quality:",prediction[0])

Predicted Wine Quality: -18830596.466497976

In [32]:
# ----(OPTIONAL)-----For Model Saving / Saving Python objects to a file for later use.

import pickle

with open("polynomial_model.pkl", "wb") as file:
    pickle.dump((poly,model), file)
    
print("Model Save Successfully")

Model Save Successfully

In [ ]:
# 11.

plt.scatter()
plt.plot()

plt.show()

<h1>TASK 3</h1>
<h3>Objective:</h3>
<h4>Consider variables x and y created from a pandas dataframe  “car.csv” .</h4>
<h3>Dataset:</h3>
<h4>car.csv</h4>
<h3>Steps to Complete the Task:</h3>
<h4>
Create new column named “Age_car” (Age_car=2023-year) <br>
For multiple linear regression problem, x contains the independent variables ( Age_car , Driven_kms , Fuel_Type , Selling_type , Transmission )  and y contains the dependent (Selling_Price) variable which is to be predicted.<br>
Write a Python program to spilt x and y into training and testing datasets with a 20% split. Then create a multiple linear regression model using the training data and print its coefficients ,intercept and mean squared error</h4>

In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [84]:
# 1. Load Dataset

df = pd.read_csv("car.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [85]:
# 2. Check Datatypes

print(df.dtypes)

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Owner              int64
dtype: object

In [86]:
# 3. Fill missing values with mean

print(df.isna().sum())

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [87]:
# 4. Create New Column → Age_car

df["Age_car"] = 2023 - df["Year"]
df.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,9

In [88]:
# 5. Drop Unnecessary Columns

# Usually Car_Name is useless for regression:

df = df.drop(["Car_Name", "Year"], axis = 1)
df.head()

,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,9

In [89]:
# 6. Handle Categorical Variables (VERY IMPORTANT)

df = pd.get_dummies(df, drop_first = True)
df

,Selling_Price,Present_Price,Kms_Driven,Owner,Age_car,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Individual,Transmission_Manual
0,3.35,5.59,27000,0,9,0,1,0,1
1,4.75,9.54,43000,0,10,1,0,0,1
2,7.25,9.85,6900,0,6,0,1,0,1
3,2.85,4.15,5200,0,12,0,1,0,1
4,4.60,6.87,42450,0,9,1,0,0,1
...,...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,0,7,1,0,0,1
297,4.00,5.90,60000,0,8,0,1,0,1
298,3.35,11.00,87934,0,14,0,1,0,1
299,11.50,12.50,9000,0,6,1,0,0,1
300,5.30,5.90,5464,0,7,0,1,0,1

In [90]:
# 7. Define Features variables (X) and  Targets (y)

X = df.drop("Selling_Price", axis = 1)
y = df["Selling_Price"]

In [91]:
# 8. Train_test_split (20% Test)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(240, 8)
(61, 8)
(240,)
(61,)

In [92]:
# OPTIONAL STEP

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn import metrics

for i in range(1,15):
    poly = PolynomialFeatures(degree = i)
    X_poly = poly.fit_transform(X)
    model = LinearRegression()
    model.fit(X_poly, y)
    y_pred = model.predict(X_poly)
    print(f"R2 Score: {i} {metrics.r2_score(y_pred, y)}")

R2 Score: 1 0.8669507363775381
R2 Score: 2 0.9816826784479126
R2 Score: 3 0.9146562212940924
R2 Score: 4 0.591139726865614
R2 Score: 5 -0.019453082061411386
R2 Score: 6 -0.976948498286371
R2 Score: 7 -1.7231207627263574
R2 Score: 8 -2.265249126241139
R2 Score: 9 -3.3575448549689986
R2 Score: 10 -3.5127496180040634
R2 Score: 11 -4.085331752650716
R2 Score: 12 -4.286257971345304
R2 Score: 13 -9.47280850759823
R2 Score: 14 -11.400004583415093

In [93]:
# 7. Polynomial Transformation (IMPORTANT)

poly = PolynomialFeatures(degree = 2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit(X_train)

In [94]:
# 8. Train Model

model = LinearRegression()
model.fit(X_train_poly, y_train)

LinearRegression()

In [117]:
# 9. Prediction

y_pred = model.predict(X_test_poly)

In [119]:
# 10. Results

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

print("MSE:", mean_squared_error(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))

print("R2 Score")

Intercept: 5.146230241092211
Coefficients: [-3.18101216e-12 -2.83934914e-12  1.05674969e-12 ... -1.30970948e-11
  4.85102732e-10  3.62670961e-12]
MSE: 5585749796484.058
MAE: 163618.33794136625