# STEP 0: UNDERSTAND YOUR DATA
    
Columns:

User ID ❌ (useless)
Gender (categorical)
Age (numeric)
EstimatedSalary (numeric)
Purchased ✅ (TARGET)

🎯 Target:

👉 Purchased

0 → Not purchased
1 → Purchased

In [18]:
# STEP 1: Import Libraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_auc_score

In [19]:
# STEP 2: Load Dataset

df = pd.read_csv("Social_Network_Ads_logistic.csv")

df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [20]:
# STEP 3: Drop Useless Column

df = df.drop('User ID', axis = 1)
df

# 👉 ID has no predictive power

     Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [21]:
# STEP 4: Encode Categorical Variable

df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

# 👉 Now all columns numeric

In [22]:
# STEP 5: Define Features & Target

X = df[['Age', 'EstimatedSalary']]

y = df['Purchased']


# 👉 Important:

# We use only relevant features
# Don’t blindly use everything

In [24]:
# STEP 6: Train-Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [8]:
# STEP 7: Feature Scaling (VERY IMPORTANT)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
# STEP 8: Train Logistic Regression Model

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [13]:
# STEP 9: MODEL PREDICTION (MAIN PART)

# Class Prediction

y_pred = model.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0], dtype=int64)

In [16]:
# Probability Prediction

y_prob = model.predict_proba(X_test)[:,1]
y_prob

# 👉 Example:
# 0.82 → 82% chance user will purchase

array([0.26465129, 0.97501265, 0.02261171, 0.85901414, 0.01627219,
       0.05806247, 0.87841508, 0.09230169, 0.39439027, 0.40771282,
       0.15145642, 0.67350714, 0.00996679, 0.00246662, 0.12336471,
       0.42472436, 0.66000992, 0.66709012, 0.15298898, 0.89669839,
       0.00413261, 0.08433092, 0.31086361, 0.96330937, 0.00178359,
       0.49380692, 0.53042626, 0.15010279, 0.98392794, 0.00190512,
       0.40261721, 0.0095334 , 0.74613443, 0.06844956, 0.65197035,
       0.19892383, 0.15872343, 0.24145117, 0.00981153, 0.00737512,
       0.43215414, 0.01514955, 0.00436161, 0.29004988, 0.00580079,
       0.92097211, 0.04687479, 0.09141979, 0.49777098, 0.06645475,
       0.03957278, 0.90961966, 0.18619453, 0.04084698, 0.30105404,
       0.01226711, 0.98686397, 0.15333629, 0.09998742, 0.10608913,
       0.26337082, 0.12053485, 0.91531451, 0.08733627, 0.03657492,
       0.29142313, 0.61112535, 0.96080443, 0.24048438, 0.37192442,
       0.98138931, 0.01554896, 0.02939831, 0.00397792, 0.39343964,
       0.09810076, 0.98976292, 0.65763368, 0.08967869, 0.28734343])

In [25]:
# STEP 10: Model Evaluation

# Accuracy

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8625

In [27]:
# Confusion Matrix

print(confusion_matrix(y_test, y_pred))

[[50  2]
 [ 9 19]]

In [28]:
# Classification Report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.96      0.90        52
           1       0.90      0.68      0.78        28

    accuracy                           0.86        80
   macro avg       0.88      0.82      0.84        80
weighted avg       0.87      0.86      0.86        80

In [29]:
# AUC Score

print("AUC core:", roc_auc_score(y_test, y_prob))

AUC core: 0.9684065934065934

In [30]:
# STEP 11: Predict NEW USER

# Example: Age = 30, Salary = 50000


new_user = [[30, 50000]]

# Apply scaling

new_user_scaled = scaler.transform(new_user)

# Predict
pred = model.predict(new_user_scaled)
prob = model.predict_proba(new_user_scaled)

print("Prediction:", pred)
print("Probability:", prob)

Prediction: [1]
Probability: [[0. 1.]]