In [1]:
import pandas as pd

In [13]:
df = pd.read_csv("netflix_titles.csv")

df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,NaN,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

# Task 1

In [11]:
# Print only the title column

print(df["title"])

0        Dick Johnson Is Dead
1               Blood & Water
2                   Ganglands
3       Jailbirds New Orleans
4                Kota Factory
                ...
8802                   Zodiac
8803              Zombie Dumb
8804               Zombieland
8805                     Zoom
8806                   Zubaan
Name: title, Length: 8807, dtype: object

# Task 2

In [16]:
# Display title and country columns together.

df[["title","country"]]

                      title        country
0      Dick Johnson Is Dead  United States
1             Blood & Water   South Africa
2                 Ganglands            NaN
3     Jailbirds New Orleans            NaN
4              Kota Factory          India
...                     ...            ...
8802                 Zodiac  United States
8803            Zombie Dumb            NaN
8804             Zombieland  United States
8805                   Zoom  United States
8806                 Zubaan          India

[8807 rows x 2 columns]

# Task 3

In [18]:
# Print the first movie title using column indexing.

df.loc[0,['title']]

title    Dick Johnson Is Dead
Name: 0, dtype: object

# Task 4

In [24]:
# Print title and release_year of the row with index 10.


df.loc[10,['title','release_year']]

title           Vendetta: Truth, Lies and The Mafia
release_year                                   2021
Name: 10, dtype: object

# Task 5

In [27]:
# Display rows from index 20 to 30 with columns:
#  title
#  release_year
#  duration


df.loc[20:30, ['title','release_year','duration']]

                                              title  release_year   duration
20  Monsters Inside: The 24 Faces of Billy Milligan          2021   1 Season
21                           Resurrection: Ertugrul          2018  5 Seasons
22                                  Avvai Shanmughi          1996    161 min
23     Go! Go! Cory Carson: Chrissy Takes the Wheel          2021     61 min
24                                            Jeans          1998    166 min
25                             Love on the Spectrum          2021  2 Seasons
26                                   Minsara Kanavu          1997    147 min
27                                        Grown Ups          2010    103 min
28                                       Dark Skies          2013     97 min
29                                         Paranoia          2013    106 min
30                                  Ankahi Kahaniya          2021    111 min

# Task 6

In [28]:
# Print title and country of index 50 using .loc.

df.loc[50, ["title","country"]]

title      Dharmakshetra
country            India
Name: 50, dtype: object